### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np
lista = np.random.randint(50, size=(10))
media = lista.mean()
desvio_padrao = np.std(lista)

print(f"A media é de {media} e o desvio padrao é de {desvio_padrao}")

A media é de 27.8 e o desvio padrao é de 15.979987484350543


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
lista = np.random.rand(10)

lista[lista<=0.5] = np.sqrt(lista[lista<=0.5])

print(lista)

[0.88486909 0.28651895 0.70453196 0.96517451 0.1192706  0.48222532
 0.50193988 0.97990127 0.23115566 0.33860016]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)
maximo = np.amax(matriz, axis = 1)

maximo

Out[23]: array([[0.97673223, 0.7464633 , 0.84719006],
       [0.48080166, 0.70185572, 0.66060102],
       [0.36349972, 0.94917994, 0.84884815]])

### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5, 5)

media = np.mean(matriz, axis=1)

media_subtraida = matriz - media[:, np.newaxis]

print(media)
print(media_subtraida)

[0.66064092 0.60907506 0.72439585 0.45838324 0.4071436 ]
[[ 0.24465993  0.08834524 -0.48777203 -0.05215248  0.20691934]
 [-0.11433149  0.25440094  0.15217719 -0.57744095  0.28519431]
 [ 0.23090016  0.10989588 -0.01758349  0.1031501  -0.42636266]
 [-0.14522382  0.31508681 -0.11569421 -0.30863046  0.25446168]
 [ 0.37816493 -0.02989188 -0.28358999  0.02753657 -0.09221964]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4)

diag_princi = np.diag(matriz)
diag_sec = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_princi, diag_sec])
desvi_padrao_diag = np.std([diag_princi, diag_sec])

print(media_diag)
print(desvi_padrao_diag)

0.4943513416713965
0.27251568332802834
